version: '3.8'
services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ambassador-db
volumes:
  postgres:
    driver: local